# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from datagit.v1 import datagit_pb2 as datagit_dot_v1_dot_datagit__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in datagit/v1/datagit_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RepositoryStub:
    """---------------------------------------------------------------------------
    Services
    ---------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateRepo = channel.unary_unary(
                '/datagit.v1.Repository/CreateRepo',
                request_serializer=datagit_dot_v1_dot_datagit__pb2.CreateRepoRequest.SerializeToString,
                response_deserializer=datagit_dot_v1_dot_datagit__pb2.RepoInfo.FromString,
                _registered_method=True)
        self.TrackTable = channel.unary_unary(
                '/datagit.v1.Repository/TrackTable',
                request_serializer=datagit_dot_v1_dot_datagit__pb2.TrackTableRequest.SerializeToString,
                response_deserializer=datagit_dot_v1_dot_datagit__pb2.TableInfo.FromString,
                _registered_method=True)
        self.UntrackTable = channel.unary_unary(
                '/datagit.v1.Repository/UntrackTable',
                request_serializer=datagit_dot_v1_dot_datagit__pb2.UntrackTableRequest.SerializeToString,
                response_deserializer=datagit_dot_v1_dot_datagit__pb2.Empty.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/datagit.v1.Repository/GetStatus',
                request_serializer=datagit_dot_v1_dot_datagit__pb2.GetStatusRequest.SerializeToString,
                response_deserializer=datagit_dot_v1_dot_datagit__pb2.RepoStatus.FromString,
                _registered_method=True)


class RepositoryServicer:
    """---------------------------------------------------------------------------
    Services
    ---------------------------------------------------------------------------

    """

    def CreateRepo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrackTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UntrackTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RepositoryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateRepo': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRepo,
                    request_deserializer=datagit_dot_v1_dot_datagit__pb2.CreateRepoRequest.FromString,
                    response_serializer=datagit_dot_v1_dot_datagit__pb2.RepoInfo.SerializeToString,
            ),
            'TrackTable': grpc.unary_unary_rpc_method_handler(
                    servicer.TrackTable,
                    request_deserializer=datagit_dot_v1_dot_datagit__pb2.TrackTableRequest.FromString,
                    response_serializer=datagit_dot_v1_dot_datagit__pb2.TableInfo.SerializeToString,
            ),
            'UntrackTable': grpc.unary_unary_rpc_method_handler(
                    servicer.UntrackTable,
                    request_deserializer=datagit_dot_v1_dot_datagit__pb2.UntrackTableRequest.FromString,
                    response_serializer=datagit_dot_v1_dot_datagit__pb2.Empty.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=datagit_dot_v1_dot_datagit__pb2.GetStatusRequest.FromString,
                    response_serializer=datagit_dot_v1_dot_datagit__pb2.RepoStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'datagit.v1.Repository', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('datagit.v1.Repository', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Repository:
    """---------------------------------------------------------------------------
    Services
    ---------------------------------------------------------------------------

    """

    @staticmethod
    def CreateRepo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datagit.v1.Repository/CreateRepo',
            datagit_dot_v1_dot_datagit__pb2.CreateRepoRequest.SerializeToString,
            datagit_dot_v1_dot_datagit__pb2.RepoInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TrackTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datagit.v1.Repository/TrackTable',
            datagit_dot_v1_dot_datagit__pb2.TrackTableRequest.SerializeToString,
            datagit_dot_v1_dot_datagit__pb2.TableInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UntrackTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datagit.v1.Repository/UntrackTable',
            datagit_dot_v1_dot_datagit__pb2.UntrackTableRequest.SerializeToString,
            datagit_dot_v1_dot_datagit__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datagit.v1.Repository/GetStatus',
            datagit_dot_v1_dot_datagit__pb2.GetStatusRequest.SerializeToString,
            datagit_dot_v1_dot_datagit__pb2.RepoStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DataStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Get = channel.unary_unary(
                '/datagit.v1.Data/Get',
                request_serializer=datagit_dot_v1_dot_datagit__pb2.GetRequest.SerializeToString,
                response_deserializer=datagit_dot_v1_dot_datagit__pb2.Row.FromString,
                _registered_method=True)
        self.Scan = channel.unary_stream(
                '/datagit.v1.Data/Scan',
                request_serializer=datagit_dot_v1_dot_datagit__pb2.ScanRequest.SerializeToString,
                response_deserializer=datagit_dot_v1_dot_datagit__pb2.Row.FromString,
                _registered_method=True)


class DataServicer:
    """Missing associated documentation comment in .proto file."""

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Scan(self, request, context):
        """Scan takes a typed filter and a cursor. The filter is applied to the
        RESOLVED row via the two-pass form, never pushed into the resolution arms
        (§7.3).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=datagit_dot_v1_dot_datagit__pb2.GetRequest.FromString,
                    response_serializer=datagit_dot_v1_dot_datagit__pb2.Row.SerializeToString,
            ),
            'Scan': grpc.unary_stream_rpc_method_handler(
                    servicer.Scan,
                    request_deserializer=datagit_dot_v1_dot_datagit__pb2.ScanRequest.FromString,
                    response_serializer=datagit_dot_v1_dot_datagit__pb2.Row.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'datagit.v1.Data', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('datagit.v1.Data', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Data:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datagit.v1.Data/Get',
            datagit_dot_v1_dot_datagit__pb2.GetRequest.SerializeToString,
            datagit_dot_v1_dot_datagit__pb2.Row.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Scan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/datagit.v1.Data/Scan',
            datagit_dot_v1_dot_datagit__pb2.ScanRequest.SerializeToString,
            datagit_dot_v1_dot_datagit__pb2.Row.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class VersionStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Commit = channel.unary_unary(
                '/datagit.v1.Version/Commit',
                request_serializer=datagit_dot_v1_dot_datagit__pb2.CommitRequest.SerializeToString,
                response_deserializer=datagit_dot_v1_dot_datagit__pb2.CommitResponse.FromString,
                _registered_method=True)
        self.Log = channel.unary_stream(
                '/datagit.v1.Version/Log',
                request_serializer=datagit_dot_v1_dot_datagit__pb2.LogRequest.SerializeToString,
                response_deserializer=datagit_dot_v1_dot_datagit__pb2.CommitInfo.FromString,
                _registered_method=True)
        self.Diff = channel.unary_stream(
                '/datagit.v1.Version/Diff',
                request_serializer=datagit_dot_v1_dot_datagit__pb2.DiffRequest.SerializeToString,
                response_deserializer=datagit_dot_v1_dot_datagit__pb2.ChangeDetail.FromString,
                _registered_method=True)
        self.Blame = channel.unary_stream(
                '/datagit.v1.Version/Blame',
                request_serializer=datagit_dot_v1_dot_datagit__pb2.BlameRequest.SerializeToString,
                response_deserializer=datagit_dot_v1_dot_datagit__pb2.CellBlame.FromString,
                _registered_method=True)
        self.History = channel.unary_stream(
                '/datagit.v1.Version/History',
                request_serializer=datagit_dot_v1_dot_datagit__pb2.HistoryRequest.SerializeToString,
                response_deserializer=datagit_dot_v1_dot_datagit__pb2.RowVersion.FromString,
                _registered_method=True)
        self.Revert = channel.unary_unary(
                '/datagit.v1.Version/Revert',
                request_serializer=datagit_dot_v1_dot_datagit__pb2.RevertRequest.SerializeToString,
                response_deserializer=datagit_dot_v1_dot_datagit__pb2.CommitResponse.FromString,
                _registered_method=True)


class VersionServicer:
    """Missing associated documentation comment in .proto file."""

    def Commit(self, request, context):
        """Commit is THE write path. It carries the whole change set: there is no
        staging on the default branch (§6.1).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Log(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Diff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Blame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def History(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Revert(self, request, context):
        """Revert adds a commit that undoes; it erases nothing.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VersionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Commit': grpc.unary_unary_rpc_method_handler(
                    servicer.Commit,
                    request_deserializer=datagit_dot_v1_dot_datagit__pb2.CommitRequest.FromString,
                    response_serializer=datagit_dot_v1_dot_datagit__pb2.CommitResponse.SerializeToString,
            ),
            'Log': grpc.unary_stream_rpc_method_handler(
                    servicer.Log,
                    request_deserializer=datagit_dot_v1_dot_datagit__pb2.LogRequest.FromString,
                    response_serializer=datagit_dot_v1_dot_datagit__pb2.CommitInfo.SerializeToString,
            ),
            'Diff': grpc.unary_stream_rpc_method_handler(
                    servicer.Diff,
                    request_deserializer=datagit_dot_v1_dot_datagit__pb2.DiffRequest.FromString,
                    response_serializer=datagit_dot_v1_dot_datagit__pb2.ChangeDetail.SerializeToString,
            ),
            'Blame': grpc.unary_stream_rpc_method_handler(
                    servicer.Blame,
                    request_deserializer=datagit_dot_v1_dot_datagit__pb2.BlameRequest.FromString,
                    response_serializer=datagit_dot_v1_dot_datagit__pb2.CellBlame.SerializeToString,
            ),
            'History': grpc.unary_stream_rpc_method_handler(
                    servicer.History,
                    request_deserializer=datagit_dot_v1_dot_datagit__pb2.HistoryRequest.FromString,
                    response_serializer=datagit_dot_v1_dot_datagit__pb2.RowVersion.SerializeToString,
            ),
            'Revert': grpc.unary_unary_rpc_method_handler(
                    servicer.Revert,
                    request_deserializer=datagit_dot_v1_dot_datagit__pb2.RevertRequest.FromString,
                    response_serializer=datagit_dot_v1_dot_datagit__pb2.CommitResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'datagit.v1.Version', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('datagit.v1.Version', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Version:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Commit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datagit.v1.Version/Commit',
            datagit_dot_v1_dot_datagit__pb2.CommitRequest.SerializeToString,
            datagit_dot_v1_dot_datagit__pb2.CommitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Log(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/datagit.v1.Version/Log',
            datagit_dot_v1_dot_datagit__pb2.LogRequest.SerializeToString,
            datagit_dot_v1_dot_datagit__pb2.CommitInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Diff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/datagit.v1.Version/Diff',
            datagit_dot_v1_dot_datagit__pb2.DiffRequest.SerializeToString,
            datagit_dot_v1_dot_datagit__pb2.ChangeDetail.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Blame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/datagit.v1.Version/Blame',
            datagit_dot_v1_dot_datagit__pb2.BlameRequest.SerializeToString,
            datagit_dot_v1_dot_datagit__pb2.CellBlame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def History(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/datagit.v1.Version/History',
            datagit_dot_v1_dot_datagit__pb2.HistoryRequest.SerializeToString,
            datagit_dot_v1_dot_datagit__pb2.RowVersion.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Revert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datagit.v1.Version/Revert',
            datagit_dot_v1_dot_datagit__pb2.RevertRequest.SerializeToString,
            datagit_dot_v1_dot_datagit__pb2.CommitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class BranchingStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateBranch = channel.unary_unary(
                '/datagit.v1.Branching/CreateBranch',
                request_serializer=datagit_dot_v1_dot_datagit__pb2.CreateBranchRequest.SerializeToString,
                response_deserializer=datagit_dot_v1_dot_datagit__pb2.RefInfo.FromString,
                _registered_method=True)
        self.DeleteBranch = channel.unary_unary(
                '/datagit.v1.Branching/DeleteBranch',
                request_serializer=datagit_dot_v1_dot_datagit__pb2.DeleteBranchRequest.SerializeToString,
                response_deserializer=datagit_dot_v1_dot_datagit__pb2.Empty.FromString,
                _registered_method=True)
        self.ListRefs = channel.unary_stream(
                '/datagit.v1.Branching/ListRefs',
                request_serializer=datagit_dot_v1_dot_datagit__pb2.ListRefsRequest.SerializeToString,
                response_deserializer=datagit_dot_v1_dot_datagit__pb2.RefInfo.FromString,
                _registered_method=True)
        self.CreateTag = channel.unary_unary(
                '/datagit.v1.Branching/CreateTag',
                request_serializer=datagit_dot_v1_dot_datagit__pb2.CreateTagRequest.SerializeToString,
                response_deserializer=datagit_dot_v1_dot_datagit__pb2.RefInfo.FromString,
                _registered_method=True)
        self.UpdateFromParent = channel.unary_unary(
                '/datagit.v1.Branching/UpdateFromParent',
                request_serializer=datagit_dot_v1_dot_datagit__pb2.UpdateFromParentRequest.SerializeToString,
                response_deserializer=datagit_dot_v1_dot_datagit__pb2.MergeResponse.FromString,
                _registered_method=True)
        self.Materialize = channel.unary_unary(
                '/datagit.v1.Branching/Materialize',
                request_serializer=datagit_dot_v1_dot_datagit__pb2.MaterializeRequest.SerializeToString,
                response_deserializer=datagit_dot_v1_dot_datagit__pb2.Empty.FromString,
                _registered_method=True)
        self.Protect = channel.unary_unary(
                '/datagit.v1.Branching/Protect',
                request_serializer=datagit_dot_v1_dot_datagit__pb2.ProtectRequest.SerializeToString,
                response_deserializer=datagit_dot_v1_dot_datagit__pb2.RefInfo.FromString,
                _registered_method=True)


class BranchingServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateBranch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteBranch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRefs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTag(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateFromParent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Materialize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Protect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BranchingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateBranch': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBranch,
                    request_deserializer=datagit_dot_v1_dot_datagit__pb2.CreateBranchRequest.FromString,
                    response_serializer=datagit_dot_v1_dot_datagit__pb2.RefInfo.SerializeToString,
            ),
            'DeleteBranch': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteBranch,
                    request_deserializer=datagit_dot_v1_dot_datagit__pb2.DeleteBranchRequest.FromString,
                    response_serializer=datagit_dot_v1_dot_datagit__pb2.Empty.SerializeToString,
            ),
            'ListRefs': grpc.unary_stream_rpc_method_handler(
                    servicer.ListRefs,
                    request_deserializer=datagit_dot_v1_dot_datagit__pb2.ListRefsRequest.FromString,
                    response_serializer=datagit_dot_v1_dot_datagit__pb2.RefInfo.SerializeToString,
            ),
            'CreateTag': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTag,
                    request_deserializer=datagit_dot_v1_dot_datagit__pb2.CreateTagRequest.FromString,
                    response_serializer=datagit_dot_v1_dot_datagit__pb2.RefInfo.SerializeToString,
            ),
            'UpdateFromParent': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateFromParent,
                    request_deserializer=datagit_dot_v1_dot_datagit__pb2.UpdateFromParentRequest.FromString,
                    response_serializer=datagit_dot_v1_dot_datagit__pb2.MergeResponse.SerializeToString,
            ),
            'Materialize': grpc.unary_unary_rpc_method_handler(
                    servicer.Materialize,
                    request_deserializer=datagit_dot_v1_dot_datagit__pb2.MaterializeRequest.FromString,
                    response_serializer=datagit_dot_v1_dot_datagit__pb2.Empty.SerializeToString,
            ),
            'Protect': grpc.unary_unary_rpc_method_handler(
                    servicer.Protect,
                    request_deserializer=datagit_dot_v1_dot_datagit__pb2.ProtectRequest.FromString,
                    response_serializer=datagit_dot_v1_dot_datagit__pb2.RefInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'datagit.v1.Branching', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('datagit.v1.Branching', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Branching:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateBranch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datagit.v1.Branching/CreateBranch',
            datagit_dot_v1_dot_datagit__pb2.CreateBranchRequest.SerializeToString,
            datagit_dot_v1_dot_datagit__pb2.RefInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteBranch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datagit.v1.Branching/DeleteBranch',
            datagit_dot_v1_dot_datagit__pb2.DeleteBranchRequest.SerializeToString,
            datagit_dot_v1_dot_datagit__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRefs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/datagit.v1.Branching/ListRefs',
            datagit_dot_v1_dot_datagit__pb2.ListRefsRequest.SerializeToString,
            datagit_dot_v1_dot_datagit__pb2.RefInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateTag(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datagit.v1.Branching/CreateTag',
            datagit_dot_v1_dot_datagit__pb2.CreateTagRequest.SerializeToString,
            datagit_dot_v1_dot_datagit__pb2.RefInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateFromParent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datagit.v1.Branching/UpdateFromParent',
            datagit_dot_v1_dot_datagit__pb2.UpdateFromParentRequest.SerializeToString,
            datagit_dot_v1_dot_datagit__pb2.MergeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Materialize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datagit.v1.Branching/Materialize',
            datagit_dot_v1_dot_datagit__pb2.MaterializeRequest.SerializeToString,
            datagit_dot_v1_dot_datagit__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Protect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datagit.v1.Branching/Protect',
            datagit_dot_v1_dot_datagit__pb2.ProtectRequest.SerializeToString,
            datagit_dot_v1_dot_datagit__pb2.RefInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SessionsStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OpenSession = channel.unary_unary(
                '/datagit.v1.Sessions/OpenSession',
                request_serializer=datagit_dot_v1_dot_datagit__pb2.OpenSessionRequest.SerializeToString,
                response_deserializer=datagit_dot_v1_dot_datagit__pb2.SessionInfo.FromString,
                _registered_method=True)
        self.SessionWrite = channel.unary_unary(
                '/datagit.v1.Sessions/SessionWrite',
                request_serializer=datagit_dot_v1_dot_datagit__pb2.SessionWriteRequest.SerializeToString,
                response_deserializer=datagit_dot_v1_dot_datagit__pb2.Empty.FromString,
                _registered_method=True)
        self.CommitSession = channel.unary_unary(
                '/datagit.v1.Sessions/CommitSession',
                request_serializer=datagit_dot_v1_dot_datagit__pb2.CommitSessionRequest.SerializeToString,
                response_deserializer=datagit_dot_v1_dot_datagit__pb2.CommitResponse.FromString,
                _registered_method=True)
        self.AbandonSession = channel.unary_unary(
                '/datagit.v1.Sessions/AbandonSession',
                request_serializer=datagit_dot_v1_dot_datagit__pb2.AbandonSessionRequest.SerializeToString,
                response_deserializer=datagit_dot_v1_dot_datagit__pb2.Empty.FromString,
                _registered_method=True)


class SessionsServicer:
    """Missing associated documentation comment in .proto file."""

    def OpenSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SessionWrite(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AbandonSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SessionsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OpenSession': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenSession,
                    request_deserializer=datagit_dot_v1_dot_datagit__pb2.OpenSessionRequest.FromString,
                    response_serializer=datagit_dot_v1_dot_datagit__pb2.SessionInfo.SerializeToString,
            ),
            'SessionWrite': grpc.unary_unary_rpc_method_handler(
                    servicer.SessionWrite,
                    request_deserializer=datagit_dot_v1_dot_datagit__pb2.SessionWriteRequest.FromString,
                    response_serializer=datagit_dot_v1_dot_datagit__pb2.Empty.SerializeToString,
            ),
            'CommitSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitSession,
                    request_deserializer=datagit_dot_v1_dot_datagit__pb2.CommitSessionRequest.FromString,
                    response_serializer=datagit_dot_v1_dot_datagit__pb2.CommitResponse.SerializeToString,
            ),
            'AbandonSession': grpc.unary_unary_rpc_method_handler(
                    servicer.AbandonSession,
                    request_deserializer=datagit_dot_v1_dot_datagit__pb2.AbandonSessionRequest.FromString,
                    response_serializer=datagit_dot_v1_dot_datagit__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'datagit.v1.Sessions', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('datagit.v1.Sessions', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Sessions:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def OpenSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datagit.v1.Sessions/OpenSession',
            datagit_dot_v1_dot_datagit__pb2.OpenSessionRequest.SerializeToString,
            datagit_dot_v1_dot_datagit__pb2.SessionInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SessionWrite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datagit.v1.Sessions/SessionWrite',
            datagit_dot_v1_dot_datagit__pb2.SessionWriteRequest.SerializeToString,
            datagit_dot_v1_dot_datagit__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datagit.v1.Sessions/CommitSession',
            datagit_dot_v1_dot_datagit__pb2.CommitSessionRequest.SerializeToString,
            datagit_dot_v1_dot_datagit__pb2.CommitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AbandonSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datagit.v1.Sessions/AbandonSession',
            datagit_dot_v1_dot_datagit__pb2.AbandonSessionRequest.SerializeToString,
            datagit_dot_v1_dot_datagit__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ProposalsStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateProposal = channel.unary_unary(
                '/datagit.v1.Proposals/CreateProposal',
                request_serializer=datagit_dot_v1_dot_datagit__pb2.CreateProposalRequest.SerializeToString,
                response_deserializer=datagit_dot_v1_dot_datagit__pb2.ProposalInfo.FromString,
                _registered_method=True)
        self.Review = channel.unary_unary(
                '/datagit.v1.Proposals/Review',
                request_serializer=datagit_dot_v1_dot_datagit__pb2.ReviewRequest.SerializeToString,
                response_deserializer=datagit_dot_v1_dot_datagit__pb2.Empty.FromString,
                _registered_method=True)
        self.ListConflicts = channel.unary_stream(
                '/datagit.v1.Proposals/ListConflicts',
                request_serializer=datagit_dot_v1_dot_datagit__pb2.ListConflictsRequest.SerializeToString,
                response_deserializer=datagit_dot_v1_dot_datagit__pb2.ConflictInfo.FromString,
                _registered_method=True)
        self.ResolveConflict = channel.unary_unary(
                '/datagit.v1.Proposals/ResolveConflict',
                request_serializer=datagit_dot_v1_dot_datagit__pb2.ResolveConflictRequest.SerializeToString,
                response_deserializer=datagit_dot_v1_dot_datagit__pb2.Empty.FromString,
                _registered_method=True)
        self.MergeProposal = channel.unary_unary(
                '/datagit.v1.Proposals/MergeProposal',
                request_serializer=datagit_dot_v1_dot_datagit__pb2.MergeProposalRequest.SerializeToString,
                response_deserializer=datagit_dot_v1_dot_datagit__pb2.MergeResponse.FromString,
                _registered_method=True)


class ProposalsServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateProposal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Review(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListConflicts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolveConflict(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MergeProposal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProposalsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateProposal': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProposal,
                    request_deserializer=datagit_dot_v1_dot_datagit__pb2.CreateProposalRequest.FromString,
                    response_serializer=datagit_dot_v1_dot_datagit__pb2.ProposalInfo.SerializeToString,
            ),
            'Review': grpc.unary_unary_rpc_method_handler(
                    servicer.Review,
                    request_deserializer=datagit_dot_v1_dot_datagit__pb2.ReviewRequest.FromString,
                    response_serializer=datagit_dot_v1_dot_datagit__pb2.Empty.SerializeToString,
            ),
            'ListConflicts': grpc.unary_stream_rpc_method_handler(
                    servicer.ListConflicts,
                    request_deserializer=datagit_dot_v1_dot_datagit__pb2.ListConflictsRequest.FromString,
                    response_serializer=datagit_dot_v1_dot_datagit__pb2.ConflictInfo.SerializeToString,
            ),
            'ResolveConflict': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveConflict,
                    request_deserializer=datagit_dot_v1_dot_datagit__pb2.ResolveConflictRequest.FromString,
                    response_serializer=datagit_dot_v1_dot_datagit__pb2.Empty.SerializeToString,
            ),
            'MergeProposal': grpc.unary_unary_rpc_method_handler(
                    servicer.MergeProposal,
                    request_deserializer=datagit_dot_v1_dot_datagit__pb2.MergeProposalRequest.FromString,
                    response_serializer=datagit_dot_v1_dot_datagit__pb2.MergeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'datagit.v1.Proposals', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('datagit.v1.Proposals', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Proposals:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateProposal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datagit.v1.Proposals/CreateProposal',
            datagit_dot_v1_dot_datagit__pb2.CreateProposalRequest.SerializeToString,
            datagit_dot_v1_dot_datagit__pb2.ProposalInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Review(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datagit.v1.Proposals/Review',
            datagit_dot_v1_dot_datagit__pb2.ReviewRequest.SerializeToString,
            datagit_dot_v1_dot_datagit__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListConflicts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/datagit.v1.Proposals/ListConflicts',
            datagit_dot_v1_dot_datagit__pb2.ListConflictsRequest.SerializeToString,
            datagit_dot_v1_dot_datagit__pb2.ConflictInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResolveConflict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datagit.v1.Proposals/ResolveConflict',
            datagit_dot_v1_dot_datagit__pb2.ResolveConflictRequest.SerializeToString,
            datagit_dot_v1_dot_datagit__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MergeProposal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datagit.v1.Proposals/MergeProposal',
            datagit_dot_v1_dot_datagit__pb2.MergeProposalRequest.SerializeToString,
            datagit_dot_v1_dot_datagit__pb2.MergeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AdminStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Prune = channel.unary_unary(
                '/datagit.v1.Admin/Prune',
                request_serializer=datagit_dot_v1_dot_datagit__pb2.PruneRequest.SerializeToString,
                response_deserializer=datagit_dot_v1_dot_datagit__pb2.PruneResponse.FromString,
                _registered_method=True)
        self.RunGC = channel.unary_unary(
                '/datagit.v1.Admin/RunGC',
                request_serializer=datagit_dot_v1_dot_datagit__pb2.RunGCRequest.SerializeToString,
                response_deserializer=datagit_dot_v1_dot_datagit__pb2.GCResponse.FromString,
                _registered_method=True)
        self.Purge = channel.unary_unary(
                '/datagit.v1.Admin/Purge',
                request_serializer=datagit_dot_v1_dot_datagit__pb2.PurgeRequest.SerializeToString,
                response_deserializer=datagit_dot_v1_dot_datagit__pb2.PurgeReceipt.FromString,
                _registered_method=True)
        self.Verify = channel.unary_stream(
                '/datagit.v1.Admin/Verify',
                request_serializer=datagit_dot_v1_dot_datagit__pb2.VerifyRequest.SerializeToString,
                response_deserializer=datagit_dot_v1_dot_datagit__pb2.VerifyFinding.FromString,
                _registered_method=True)
        self.Export = channel.unary_stream(
                '/datagit.v1.Admin/Export',
                request_serializer=datagit_dot_v1_dot_datagit__pb2.ExportRequest.SerializeToString,
                response_deserializer=datagit_dot_v1_dot_datagit__pb2.ExportChunk.FromString,
                _registered_method=True)


class AdminServicer:
    """Missing associated documentation comment in .proto file."""

    def Prune(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunGC(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Purge(self, request, context):
        """Purge requires the separate `purge` capability, deliberately not bundled
        with admin (§15.3).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Verify(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Export(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdminServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Prune': grpc.unary_unary_rpc_method_handler(
                    servicer.Prune,
                    request_deserializer=datagit_dot_v1_dot_datagit__pb2.PruneRequest.FromString,
                    response_serializer=datagit_dot_v1_dot_datagit__pb2.PruneResponse.SerializeToString,
            ),
            'RunGC': grpc.unary_unary_rpc_method_handler(
                    servicer.RunGC,
                    request_deserializer=datagit_dot_v1_dot_datagit__pb2.RunGCRequest.FromString,
                    response_serializer=datagit_dot_v1_dot_datagit__pb2.GCResponse.SerializeToString,
            ),
            'Purge': grpc.unary_unary_rpc_method_handler(
                    servicer.Purge,
                    request_deserializer=datagit_dot_v1_dot_datagit__pb2.PurgeRequest.FromString,
                    response_serializer=datagit_dot_v1_dot_datagit__pb2.PurgeReceipt.SerializeToString,
            ),
            'Verify': grpc.unary_stream_rpc_method_handler(
                    servicer.Verify,
                    request_deserializer=datagit_dot_v1_dot_datagit__pb2.VerifyRequest.FromString,
                    response_serializer=datagit_dot_v1_dot_datagit__pb2.VerifyFinding.SerializeToString,
            ),
            'Export': grpc.unary_stream_rpc_method_handler(
                    servicer.Export,
                    request_deserializer=datagit_dot_v1_dot_datagit__pb2.ExportRequest.FromString,
                    response_serializer=datagit_dot_v1_dot_datagit__pb2.ExportChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'datagit.v1.Admin', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('datagit.v1.Admin', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Admin:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Prune(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datagit.v1.Admin/Prune',
            datagit_dot_v1_dot_datagit__pb2.PruneRequest.SerializeToString,
            datagit_dot_v1_dot_datagit__pb2.PruneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunGC(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datagit.v1.Admin/RunGC',
            datagit_dot_v1_dot_datagit__pb2.RunGCRequest.SerializeToString,
            datagit_dot_v1_dot_datagit__pb2.GCResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Purge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datagit.v1.Admin/Purge',
            datagit_dot_v1_dot_datagit__pb2.PurgeRequest.SerializeToString,
            datagit_dot_v1_dot_datagit__pb2.PurgeReceipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Verify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/datagit.v1.Admin/Verify',
            datagit_dot_v1_dot_datagit__pb2.VerifyRequest.SerializeToString,
            datagit_dot_v1_dot_datagit__pb2.VerifyFinding.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Export(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/datagit.v1.Admin/Export',
            datagit_dot_v1_dot_datagit__pb2.ExportRequest.SerializeToString,
            datagit_dot_v1_dot_datagit__pb2.ExportChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
